### ISSUE TITLE
Any way to build this without using Cocoa-pods? 

### ISSUE THREAD

**Issue by Motti-Shneor** [googlecast/CastVideos-ios#10]
After all the google site tells you how to add the cast API SDK framework into your iOS app, both directly in Xcode and via cocoa-pods. But this sample just bases upon pods.

Any quick recipe for doing this without cocoa-pods?

**Comment by LeonNicholls** [comment]
Our docs do cover the manual steps to include the Cast framework in your app: https://developers.google.com/cast/docs/ios_sender_setup

**Comment by Motti-Shneor** [comment]
Yes - but the sample iOS project is fully aligned (scripts and all) with Cocoa-pods installation, dependency and build of the SDK.

It would be nice to also suggest a standalone version that works without the need for Cocoa-pods. 

Many large projects (such as the AT&T project I work on) cannot involve cocoa-pods into the distributed teams workflow, the automated build machine schemes and so on. We usually prefer the “bare-bones” Xcode-only way.

I have been able to clean-up the sample project, and change it to work with the framework SDK, but it took me some time and struggle to find and remove all the scripts and steps and references and .xcconfig base. Would be nicer to have a clear version to start with.

There is still something I don’t understand. When I run the sample sender app, I can see and select 2 cast-receiver items - which are not real as far as I can tell - there’s no “Nexus” and no “Television 131” in our office… is the sample functional at all?  To what degree?

**Comment by LeonNicholls** [comment]
The sample is fully functional and used as the starting point for many of our partners apps. You can file any issues against the Cast SDK: https://code.google.com/p/google-cast-sdk/issues/list
