### ISSUE TITLE
Adding to queue adds current playing

### ISSUE THREAD

**Issue by RWOverdijk** [googlecast/CastVideos-ios#11]
I'm testing this project and whenever I add something to the queue, it doesn't add the video I want it to add, but instead it adds another entry of the already playing item.

![screenshot 2017-03-02 12 45 01](https://cloud.githubusercontent.com/assets/781745/23505946/16fbacae-ff46-11e6-8be9-1748cc9f8154.png)

**Comment by LeonNicholls** [comment]
Please try latest version of the Cast SDK.

**Comment by RWOverdijk** [comment]
No.
