### ISSUE TITLE
Device chooser navigation bar become transparent

### ISSUE THREAD

**Issue by Blurzschyter** [googlecast/CastVideos-ios#110]
Hi,

When I compiled the codelabs code on my iPhone 8 Plus (ios 15.0.2), the navigation bar on deviceChooser become transparent. Is it supposed to displayed like that or not?

![IMG_39B5F76ACCC4-1](https://user-images.githubusercontent.com/23515008/141645618-a3e3e048-084b-42e8-b7d7-3d907f5a73f1.jpeg)

Is it possible to change/update the navigation bar background color? There is no info mention about the navigation bar ui styles modification on https://developers.google.com/cast/docs/ios_sender/customize_ui section.

Appreciate if anyone can advice on my problem. Im using Xcode 13.0.
Thank you in advance ^_^

**Comment by bradoutlaw** [comment]
Thank you for reporting.  This is a known issue.  Our iOS Sender SDK release 4.7.0 has a fix for this.  Please keep an eye out for the release.  (It should release later today.)

**Comment by jtromo** [comment]
Closing issue as the newest release should provide a fix. Please reopen if issue persists.
