### ISSUE TITLE
Add arm64 simulator architecture to the binary

### ISSUE THREAD

**Issue by psiwork** [googlecast/CastVideos-ios#113]
Current framework cannot be compiled on arm64 simulator being ran by M1 machine. It contains two arches: x86 and arm64. Please compile it also for arm64 simulator support.

**Comment by mkuliszkiewicz** [comment]
I'd like to bump this request, we are unable to compile for simulator on M1 Macs

**Comment by jtromo** [comment]
We've added a beta version of the Cast iOS SDK with M1 support to the developer site that can be added manually: https://developers.google.com/cast/docs/ios_sender#xcframework_beta

Please reopen if you run into issues
