### ISSUE TITLE
Upgrade from iPadOS 14.4 to 14.6/7 and now 15+  broke casting on all applications.

### ISSUE THREAD

**Issue by MishuGrig** [googlecast/CastVideos-ios#115]
Ipad 6th generation with hd Chromecast.
Apps tested netflix,youtube, hbo etc.

**Comment by gomez-andres** [comment]
Hi [MishuGrig](https://github.com/MishuGrig) thank you for the feedback. This issue tracker is meant for the sample iOS sender app code. If you are experiencing issues on other apps please file a bug on the [public issue tracker](https://cast.google.com/publish/#/support).
