### ISSUE TITLE
Using example app. Error: "Media failed to load"

### ISSUE THREAD

**Issue by reeq-dev** [googlecast/CastVideos-ios#117]
https://user-images.githubusercontent.com/26365596/152839766-08d6819c-c8fc-4f5e-a071-44b65d2e86b5.MP4

<img width="1638" alt="image" src="https://user-images.githubusercontent.com/26365596/152839241-120d9f89-160c-42c0-bcd4-591c176a6230.png">

Xcode: 13.2.1 (13C100)
Device: iPhone 11
Device OS version: 15.2.1

**Comment by vpunjabi** [comment]
Which receiver id are you using? Which device are you casting to?

**Comment by reeq-dev** [comment]
That was plain android device with cast receiver app:
https://play.google.com/store/apps/details?id=com.softmedia.receiver.castapp&hl=en&gl=US&pli=1
For regular receiver device - everything works fine.
