### ISSUE TITLE
How to play Youtube video to GoogleCrome cast.

### ISSUE THREAD

**Issue by BhaveshNai** [googlecast/CastVideos-ios#118]
How to play Youtube or similar website video to GoogleCrome cast. ??

**Comment by vpunjabi** [comment]
If you have any developer related questions to iOS for cast please create another issue under this [CastVideos-ios](https://github.com/googlecast/CastVideos-ios) repo.
If you are trying to cast YouTube please refer to the [support page](https://support.google.com/chromecast/answer/2995235?hl=en).
