### ISSUE TITLE
kGCKMediaDefaultReceiverApplicationID won't work with castVideos ios

### ISSUE THREAD

**Issue by alexrmacleod** [googlecast/CastVideos-ios#12]
Looking to get the default media receiver app to work with my iOS chromecast sender application.

Got my app running however when I switch from the default app id `return prefApplicationID` to `kGCKMediaDefaultReceiverApplicationID` my sender app or the default media receiver app doesn't seem to load the url? What am I missing, I have read like all the documentation. 

[https://developers.google.com/cast/docs/receiver_apps#default](https://developers.google.com/cast/docs/receiver_apps#default
)

Also the debugger notes don't seem to work, `http://192.168.1.140:9222/ `is my IP of my chrome cast? What am I missing here, I get a connect err?

Below is the Swift code I use to create and send the media to my cast device, works with the castVideos app id. but need it to work with ``kGCKMediaDefaultReceiverApplicationID``

`

// MARK: - decoding google cast item
            private var trackStyle: GCKMediaTextTrackStyle!
            
            func decodeMediaTree(videoData data: VideoData) -> MediaItem {
                let rootItem = MediaItem(title: nil, imageURL: nil, parent: nil)
                
                self.title = data.title
                // Pick the MP4 files only
                let videosBaseURL = URL(string: "https://commondatastorage.googleapis.com/gtv-videos-bucket/CastVideos/mp4/")
                let imagesBaseURL = URL(string: "https://commondatastorage.googleapis.com/gtv-videos-bucket/CastVideos/images/")
                let tracksBaseURL = URL(string: "https://commondatastorage.googleapis.com/gtv-videos-bucket/CastVideos/tracks/")
                self.decodeItemList(videoData: data, into: rootItem, videoFormat: kKeyMP4BaseURL,
                                    videosBaseURL: videosBaseURL!, imagesBaseURL: imagesBaseURL!, tracksBaseURL: tracksBaseURL!)
                return rootItem
            }
            
            func buildURL(with string: String?) -> URL? {
                guard let string = string else { return nil }
                return URL(string: string)!
            }
            
            func decodeItemList(videoData data: VideoData, into item: MediaItem, videoFormat: String,
                                videosBaseURL: URL, imagesBaseURL: URL, tracksBaseURL: URL) {
                let metadata = GCKMediaMetadata(metadataType: .movie)
                if isTrailer {
                    metadata.setString("Trailer: " + data.title, forKey: kGCKMetadataKeyTitle)
                } else {
                    metadata.setString(data.title, forKey: kGCKMetadataKeyTitle)
                }
                
                var mimeType: String? = nil
                var url: URL? = nil
                var duration:Int? = nil
                mimeType = "videos/mp4"
        //        let urlText: String? = "DesigningForGoogleCast.mp4"
                if isTrailer {
                    url = self.buildURL(with:data.trailer)
                    duration = Int(getMediaDuration(url: URL(string: data.trailer)))
                } else {
                    url = self.buildURL(with:data.url)
                    duration = Int(getMediaDuration(url: URL(string: data.url)))
                }
                
                let imageURLString: String? = data.img
                if let imageURL = self.buildURL(with: imageURLString) {
                    metadata.addImage(GCKImage(url: imageURL, width: kThumbnailWidth, height: kThumbnailHeight))
                }
                let posterURLText: String? = data.img
                if let posterURL = self.buildURL(with: posterURLText) {
                    metadata.setString(posterURL.absoluteString, forKey: kMediaKeyPosterURL)
                    metadata.addImage(GCKImage(url: posterURL, width: kPosterWidth, height: kPosterHeight))
                }
                
                var mediaTracks: [GCKMediaTrack]? = nil
                var studio = ""
                var description = ""
                
                if isTv! {
                    studio = data.episode + ", " + data.imdb
                    description = data.episode + ": " + data.desc
                } else { // if movie
                    studio = data.imdb
                    description = data.desc
                }
                    metadata.setString(studio, forKey: kGCKMetadataKeyStudio)
                    metadata.setString(description, forKey: kMediaKeyDescription)

                mediaTracks = [GCKMediaTrack]()
        //        guard let trackDict = trackElement as? NSDictionary else { continue }
                let identifier = 1
                let name: String? = "English Subtitle"
                let typeString: String? = "text"
                let subtypeString: String? = "captions"
                let contentID: String? = "DesigningForGoogleCast-en.vtt"
                let language: String? = "en-US"
                let captionUrl = self.buildURL(with: "https://commondatastorage.googleapis.com/gtv-videos-bucket/CastVideos/tracks/\(contentID!)")
                let mediaTrack = GCKMediaTrack(identifier: identifier, contentIdentifier: nil,
                                               contentType: kDefaultTrackMimeType, type: self.trackType(from: typeString!),
                                               textSubtype: self.textTrackSubtype(from: subtypeString!),
                                               name: name, languageCode: language, customData: nil)
                mediaTracks?.append(mediaTrack)
                
                if mediaTracks?.count == 0 {
                    mediaTracks = nil
                }
                let mediaInfo = GCKMediaInformation(contentID: url!.absoluteString, streamType: .buffered,
                                                    contentType: mimeType!, metadata: metadata,
                                                    streamDuration: TimeInterval(duration!),
                                                    mediaTracks: mediaTracks,
                                                    textTrackStyle: self.trackStyle, customData: nil)
                let childItem = MediaItem(mediaInformation: mediaInfo, parent: item)
                self.mediaInfo = childItem.mediaInfo!
                item.children.append(childItem)
                
                //ActionSheet asking user to add to play cast or add to que
                if !isTrailer { self.continueAfterPlayButtonClicked() }
            }
            
            func trackType(from string: String) -> GCKMediaTrackType {
                if string == "audio" {
                    return .audio
                }
                if string == "text" {
                    return .text
                }
                if string == "video" {
                    return .video
                }
                return .unknown
            }
            
            func textTrackSubtype(from string: String) -> GCKMediaTextTrackSubtype {
                if string == "captions" {
                    return .captions
                }
                if string == "chapters" {
                    return .chapters
                }
                if string == "descriptions" {
                    return .descriptions
                }
                if string == "metadata" {
                    return .metadata
                }
                if string == "subtitles" {
                    return .subtitles
                }
                return .unknown
            }
            
            func getMediaDuration(url: URL!) -> Double {
                let asset : AVURLAsset = AVURLAsset(url: url) as AVURLAsset
                let duration : CMTime = asset.duration
                return Double(CMTimeGetSeconds(duration))
            }
            
            // The media to play.
            var mediaInfo: GCKMediaInformation? {
                didSet {
                    print("setMediaInfo")
                }
            }
            
            func continueAfterPlayButtonClicked() -> Bool {
                UIApplication.shared.isNetworkActivityIndicatorVisible = false
                let hasConnectedCastSession = GCKCastContext.sharedInstance().sessionManager.hasConnectedCastSession
                print("continueAfterPlayButtonClicked")
                print("videoDetected \(videoDetected)")
                print("isTrailer \(isTrailer)")
                print("hasConnectedCastSession \(hasConnectedCastSession())")
                print("self.mediaInfo \(self.mediaInfo)")
                if (self.mediaInfo != nil) && hasConnectedCastSession() {
                    // Display an alert box to allow the user to add to queue or play
                    // immediately.
                    self.actionSheet = ActionSheet(title: actionSheetData["title"]!, message: actionSheetData["message"]!, cancelButtonText: "Cancel")
                    // Toggel acction depending if trailer is clicked
                    if isTrailer {
                        self.actionSheet?.addAction(withTitle: "Play Trailer", target: self, selector: #selector(self.playTrailer))
                    } else {
                        self.actionSheet?.addAction(withTitle: "Play Now", target: self, selector: #selector(self.playSelectedItemRemotely))
                    }
                    isTrailer = false
                    self.actionSheet?.addAction(withTitle: "Add to Queue", target: self, selector: #selector(self.enqueueSelectedItemRemotely))
        //            if isTrailer {
        //                self.actionSheet?.addAction(withTitle: "Trailer", target: self, selector: #selector(self.playTrailer))
        //            }
        //            self.actionSheet?.present(in: self, sourceView: self._localPlayerView)
                    self.actionSheet?.present(in: self, sourceView: self.view)
                    return false
                }
                
                // Ask user to connect cast if they haven't already
                // videoDetected is to stop this actionsheet from opening on launch
                else if !hasConnectedCastSession() && videoDetected == true {
                    self.actionSheet = ActionSheet(title: actionSheetData["title"]!, message: "Please connect to your chromecast", cancelButtonText: "Cancel")
                    self.actionSheet?.addAction(withTitle: "Connect to Chromecast", target: self, selector: #selector(self.connectToChromecast))
        //            self.actionSheet?.present(in: self, sourceView: self._localPlayerView)
                    self.actionSheet?.present(in: self, sourceView: self.view)
                }
                return true
            }
            
            func playSelectedItemRemotely() {
                self.loadSelectedItem(byAppending: false)
                GCKCastContext.sharedInstance().presentDefaultExpandedMediaControls()
            }
            
            func enqueueSelectedItemRemotely() {
                self.loadSelectedItem(byAppending: true)
                let message = "Added \"\(self.mediaInfo?.metadata?.string(forKey: kGCKMetadataKeyTitle) ?? "")\" to queue."
                if let window = UIApplication.shared.delegate?.window {
                    Toast.displayMessage(message, for: 3, in: window)
                }
                self.setQueueButtonVisible(true)
            }
            
            func playTrailer() {
                if self.data.trailer.isEmpty {
                    print("self.data.trailer is blocking: \(self.data.trailer)")
                    return
                }
                self.loadSelectedItem(byAppending: false)
                GCKCastContext.sharedInstance().presentDefaultExpandedMediaControls()
            }
            
            func connectToChromecast() {
                castButton.sendActions(for: .touchUpInside)
            }
            
            /**
             * Loads the currently selected item in the current cast media session.
             * @param appending If YES, the item is appended to the current queue if there
             * is one. If NO, or if
             * there is no queue, a new queue containing only the selected item is created.
             */
            
            func loadSelectedItem(byAppending appending: Bool) {
                print("enqueue item \(String(describing: self.mediaInfo?.metadata?.string(forKey: kGCKMetadataKeyArtist)))")
                if let remoteMediaClient = GCKCastContext.sharedInstance().sessionManager.currentCastSession?.remoteMediaClient {
                    let builder = GCKMediaQueueItemBuilder()
                    builder.mediaInformation = self.mediaInfo
                    builder.autoplay = true
                    builder.preloadTime = TimeInterval(UserDefaults.standard.integer(forKey: kPrefPreloadTime))
                    let item = builder.build()
                    if ((remoteMediaClient.mediaStatus) != nil) && appending {
                        let request = remoteMediaClient.queueInsert(item, beforeItemWithID: kGCKMediaQueueInvalidItemID)
                        request.delegate = self
                    } else {
                        let repeatMode = remoteMediaClient.mediaStatus?.queueRepeatMode ?? .off
                        let request = remoteMediaClient.queueLoad([item], start: 0, playPosition: 0,
                                                                  repeatMode: repeatMode, customData: nil)
                        request.delegate = self
                        print(request)
                    }
                }
            }

`

**Comment by LeonNicholls** [comment]
There is no need to cross post the same issue.

**Comment by alexrmacleod** [comment]
@entertailion but you closed all of them :( maybe leave one open?

Any chance of some guidance or advice on how to get castVideos-ios working with kGCKMediaDefaultReceiverApplicationID?

**Comment by alexrmacleod** [comment]
@entertailion oh I saw your other post
