### ISSUE TITLE
Local Subtitle files

### ISSUE THREAD

**Issue by ghost** [googlecast/CastVideos-ios#14]
Does the SDK support adding local .vtt subtitles. In the example you give you're loading them from a remote url. 

I have tried passing in the absoluteString value (looks something like this: **file:///private/var/mobile/Containers/Data/Application/AACAA839-D488-4940-BF6A-233866C2D5A4/tmp/Downloads/8d9da6f349fc3993/Deadpool%20(2016)%20%5BYTS.AG%5D/Subtitles/Deadpool.2016.1080p.BluRay.x265.ShAaNiG.vtt**). 

Is this supported? Do I need to remove the percent encoding?

**Comment by alexrmacleod** [comment]
@FlaviaBondJamesBondsHusband exact same issue here. Please let me know if you figure this one out! 

My question about srt to vtt, without hosting. 
[https://github.com/googlecast/CastVideos-ios/issues/13](url)

**Comment by LeonNicholls** [comment]
The receiver loads the VTT file, so it needs to be a URL accessible from the Cast device.
