### ISSUE TITLE
How to get the media data readily available?

### ISSUE THREAD

**Issue by kilirushi** [googlecast/CastVideos-ios#16]
I want to get time ranges for which the player has the media data readily available. Cast sdk was support?.
Please see img below:
![simulator screen shot jun 7 2017 14 08 32](https://user-images.githubusercontent.com/17327812/26866369-085bfb72-4b8b-11e7-8dec-2141d8fccc0e.png)

**Comment by LeonNicholls** [comment]
You can get the media metadata from: https://developers.google.com/cast/docs/reference/ios/interface_g_c_k_media_status
