### ISSUE TITLE
Couldn't cast video from google drive with subtitles

### ISSUE THREAD

**Issue by ghost** [googlecast/CastVideos-ios#17]
I used video streaming from google drive: e.g: https://redirector.googlevideo.com/videoplayback?id=6cab7cb4278cffe1&itag=22&source=webdrive&requiressl=yes&ttl=transient&pl=33&ei=O1M7WY_pKZLh-gPnir7IDA&mime=video%2Fmp4&lmt=1496395916737439&ip=2600%3A3c01%3A%3Af03c%3A91ff%3Afe60%3Acdb7&ipbits=0&expire=1497074555&sparams=api,ei,expire,id,ip,ipbits,itag,lmt,mime,mm,mn,ms,mv,pl,requiressl,source,ttl&signature=027E2A2DF78EA29BB2593BCED5D8BA94BD6FA704.609B7A6E4B9E40472BB8E1714BBDAE242C70F16B&api=AF4A92CAFE83CD24BEBCE98382E0A&cms_redirect=yes&mm=31&mn=sn-n4v7sn7z&ms=au&mt=1497060030&mv=m&key=cms1&app=storage
(the above url is playing well now, but when you see it maybe is expired)
and the subtitles I used as: https://commondatastorage.googleapis.com/gtv-videos-bucket/CastVideos/tracks/GoogleIO-2014-CastingToTheFuture2-en.vtt
--> result: couldn't cast video & subtitles 
It only work if I use video from https://commondatastorage.googleapis.com/gtv-videos-bucket/CastVideos/mp4/DesigningForGoogleCast.mp4

Please help me!

**Comment by ghost** [comment]
hi you guys, can you help me?

**Comment by LeonNicholls** [comment]
This is very likely a CORS configuration issue. You will need to host the video and the subtitles on the same server or on servers that you can change the CORS configuration.
