### ISSUE TITLE
Cast button not showing up

### ISSUE THREAD

**Issue by tobitech** [googlecast/CastVideos-ios#18]
There is the code to add the cast button to the view controllers as UIBarButtonItem, but when i run the app it doesn't show up.Could I be missing something?

**Comment by LeonNicholls** [comment]
If you run the sample app as-is with your app id, does the Cast icon display?

**Comment by tobitech** [comment]
I was actually running it on a simulator, that was why. 
The issue i have now is getting it to show on an existing project (it does show for the sample project). I added the context in app delegate and then the cast button in a view controller but doesn't appear. I'm I missing something?

**Comment by LeonNicholls** [comment]
It is very import that you initialize the Cast context as early as possible in the app lifecycle.

**Comment by tobitech** [comment]
I did that but still not showing up. 
I added this code inside my didFinishLaunchingWithOptions
`let options = GCKCastOptions(receiverApplicationID: applicationID)
        GCKCastContext.setSharedInstanceWith(options)
        GCKLogger.sharedInstance().delegate = self`
and this in my View Controller
`
        let frame = CGRect(x: 0, y: 0, width: 24, height: 24)
        let castButton = GCKUICastButton(frame: frame)
        let item = UIBarButtonItem(customView: castButton)
        self.navigationItem.rightBarButtonItem = item`
It was showing up in the sample project before but it's not showing anymore. I'm running the app on an iPad Mini.
This below is printed out to the console
`Logging 5, currently detected {(
    1,
    5
)}`

**Comment by LeonNicholls** [comment]
Its very difficult to understand why it isn't working without seeing all of your code. The best advice I can give is to study the sample app line-by-line since that works for your app id.

**Comment by tobitech** [comment]
Okay, I've solved it. It was because the cast device wasn't setup to connect on the same network with my phone. Thanks for the support.

**Comment by tobitech** [comment]
Hello, i was following the tutorial on the code lab, when i got to the point of casting the media, it was said that one should "Create a GC Media Information object from the Cast SDK that models a media item"... Could you please explain how am suppose to do this with an existing Media object model?

**Comment by LeonNicholls** [comment]
Have you looked at the sample app on how to do that?

**Comment by Jignesh1805** [comment]
self.castButton = GCKUICastButton(frame: CGRect(x: CGFloat(0), y: CGFloat(0), width: CGFloat(24), height: CGFloat(24)))

*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSArrayM insertObject:atIndex:]: object cannot be nil'

How to solve this error ? in cast button

**Comment by jtromo** [comment]
Please add a breakpoint and confirm which object is nil. Your snippet should create a valid cast button.

**Comment by Jignesh1805** [comment]
I am already have break point in this snippet but crash this line.

**Comment by soberman** [comment]
Make sure your app is being initialized properly, make sure your breakpoint in `didFinishLaunchingWithOptions` is being hit.

**Comment by tarikdedic** [comment]
Might sound trivial, but if you have followed the tutorial correctly try restarting WiFi on your phone.
After wifi restart cast button showed up for me. I know the issue is closed but this might help someone.

**Comment by JigarPrajapati21** [comment]
Hello sir i have issue when i tap on gckuicastbutton then it's ask for permission then i will tap on ok button that  gckuicastbutton is hide automatically
