### ISSUE TITLE
Cast button not showing up on simulator

### ISSUE THREAD

**Issue by gulfbing** [googlecast/CastVideos-ios#19]
After updating Cast iOS Sender API Libraries from 3.5.0 to 3.5.2, or 3.5.3, I no longer get a cast button when running on simulator. Neither in our app nor in the sample app.

**Comment by LeonNicholls** [comment]
But 3.5.0 still works for you?

**Comment by gulfbing** [comment]
Yes. And it works on device with 3.5.2 and 3.5.3, but not simulator.

**Comment by LeonNicholls** [comment]
This sounds like an issue with the Cast SDK and not the sample. Please file an issue: https://issuetracker.google.com/issues?q=componentid:190205%20status:open&s=modified_time:desc
