### ISSUE TITLE
cast button not visible?

### ISSUE THREAD

**Issue by CapnSpellcheck** [googlecast/CastVideos-ios#2]
I'm running the app in iOS simulator (iOS 9.0) and there's no cast button visible on the nav bar. It seems that the button is thus rendered onclickable. But the app did show the 'tap here to cast' intro. So why is the button image not showing up?

Inside [MediaTableViewController viewWillAppear:] I put a breakpoint and logged the folllowing

(lldb) po _castButton.imageView
`<UIImageView: 0x7fd5e0592110; frame = (0 0; 0 0); clipsToBounds = YES; hidden = YES; opaque = NO; userInteractionEnabled = NO; layer = <CALayer: 0x7fd5e05926b0>>`

(lldb) po _castButton.imageView.image
 nil
(lldb)

**Comment by CapnSpellcheck** [comment]
Nevermind

**Comment by worksdelight** [comment]
@CapnSpellcheck  how did you solve i am experiencing the same issue >
Thanks in advance.

**Comment by CapnSpellcheck** [comment]
I changed Wifi network, the Cast Now dialog always shows up, even when you are not on the same Wifi network.
