### ISSUE TITLE
Large text size setting makes the titles in the mini controller intersect

### ISSUE THREAD

**Issue by gulfbing** [googlecast/CastVideos-ios#20]
If a large text size is selected on iPhone, by going to Settings / Display & Brightness / Text Size and dragging the slider to the far right, the 2 title rows displayed in the mini controller starts to intersect, that is partly covers each other. Tested on iPhone 7 in portrait, but probably same problem on all iPhones.

**Comment by LeonNicholls** [comment]
Please file a bug against the Cast SDK: https://issuetracker.google.com/issues?q=componentid:190205%20status:open&s=modified_time:desc
