### ISSUE TITLE
Cast session getting suspended due to “GCKConnectionSuspendReasonNetworkNotReachable”

### ISSUE THREAD

**Issue by dadheech115** [googlecast/CastVideos-ios#22]
Observed behavior: After starting the casting of music files, user enters the background. After a few minutes of playing the music file through cast, session gets suspended with the reason GCKConnectionSuspendReasonNetworkNotReachable, even though the sender device and cast device both are connected to a working Wi-Fi connection

Expected Behavior: The session should continue as the sender app has the background capability of playing audio and also with GCKCastOptions we have set the property suspendSessionsWhenBackgrounded to NO.

**Comment by LeonNicholls** [comment]
This is by design. The framework automatically suspends sessions when the sender app is going into the background and attempts to resume them when the app returns to the foreground (or is relaunched after an abnormal/abrupt app termination while a session was active).

**Comment by dadheech115** [comment]
HI @entertailion , Please check the April 12 release notes here https://developers.google.com/cast/docs/release-notes

In sender sdk for ios version 3.4 . 

They have changed the behaviour. So I am just looking for reason why this thing is not working with latest SDK and sender app. And also this is not working for my own app.

**Comment by LeonNicholls** [comment]
Please file a bug against the SDK: https://issuetracker.google.com/issues?q=componentid:190205%20status:open&s=modified_time:desc
