### ISSUE TITLE
Cast icon is invisible when the device is awakened

### ISSUE THREAD

**Issue by AvdLee** [googlecast/CastVideos-ios#23]
As reported by Google to us, reproduced in this project as well. Defined as an SDK issue:

Chromecast Build:27946
Device : iPad mini iOS 8.1.1
             iPhone 5 iOS 8.1.1

Steps to Reproduce:
1.Launch app
2.Tap on Cast icon and select available chromecast device
3.Select any content and tap on Play icon
>>Receiver loads the content 
4.Allow the device to sleep mode
5.After 15 mins of casting,Unlock the device
>>Sender displays Expanded control screen
6.Tap on back button
7.Observe Sender app

Actual Result:
Cast icon is invisible locally but casting continues on receiver.  Need to relaunch the app to view the cast icon 

Expected Result:
Display the cast icon when the device is awakened 

Occurrence : 4 out of 5

**Comment by ianbarber** [comment]
When the device is backgrounded, it will disconnect, and when the device awakens it will attempt to scan for devices and automatically reconnect. Because the backgrounding is an implicit disconnect, casting will continue on the receiver. 

Does the cast icon reappear after a minute or two? If it does, at that point it should reconnect. 

The sender should bounce back from the expanded control screens regardless if the connection isn't restablishes though - I will attempt to repro that.

**Comment by AvdLee** [comment]
It tries to reconnect, but without success. Attached the logging:

https://dl.dropboxusercontent.com/u/11986023/Issue%2022140%20-%20Debug%20log.rtf

**Comment by pjcau** [comment]
Hi guys, 

I have the same problems on some apple devices. There is also strange case. 
If the sender is connect to receiver and there is a casting, now you kill the app from sender, when you restart the app there is some time before to retrieve the other chromecasts  and to reconnect. The problem obviously is that the app discover so long delay the chromecasts.

**Comment by ianbarber** [comment]
Looking at that log it looks like there is an explicit disconnect in there as well. Can you check if the same thing happens with the latest 2.6.0 version of the SDK? I haven't had a clean repro so far, but if it is a timing thing could be more subtle.

**Comment by pjcau** [comment]
Hi, 
I think that disconnect with explicit and I attach the logs when the app go in background:

-[GCKDeviceManager appDidEnterBackground]  appDidEnterBackground
- Connection Suspended: App Backgrounded
-[GCKDeviceManager disconnectInternalUncheckedWithExplicitFlag:]  
-[GCKCastSecureSocket disconnectWithError:]  disconnect
-[GCKCastSecureSocket doTeardownWithErrorCode:]  doTeardownWithErrorCode:0
-[GCKClearcutLogger closeLogWriters]  closeLogWriters
-[GCKDeviceManager castSocket:didDisconnectWithError:]  castSocket:didDisconnectWithError:
-[GCKHeartbeatChannel didDisconnect]  disconnected - stopping heartbeat timer if necessary
-[GCKDeviceManager handleConnectionError:]  handleConnectionError error=(null), 
-[GCKCastSecureSocket disconnectWithError:]  disconnect

And  I'm using the last SDK 2.6.0.

**Comment by ianbarber** [comment]
Should be fixed in the latest version (and notably SDK 2.6.1)
