### ISSUE TITLE
remoteMediaClient.mediaStatus is nill

### ISSUE THREAD

**Issue by dadheech115** [googlecast/CastVideos-ios#23]
Upon resumption of a session, when I try to access this property to move to current playing item on sender app, I get media status as nill. Any possible reasons as why is it like this?

**Comment by LeonNicholls** [comment]
Is this issue happening in the sample app or your own app?

**Comment by dadheech115** [comment]
Well this is happening in sample app as well with the latest sdk.

**Comment by LeonNicholls** [comment]
Please file a bug against the SDK: https://issuetracker.google.com/issues?q=componentid:190205%20status:open&s=modified_time:desc
