### ISSUE TITLE
lastKnownStreamPosition returning NaN

### ISSUE THREAD

**Issue by Dan-Rodriguez** [googlecast/CastVideos-ios#24]
I've noticed that "lastKnownStreamPosition" always returns "NaN" hence the local player won't continue playing where the remote player left of. I'm trying to find information on the matter and wasn't able to find anything helpful.

**Comment by gurhub** [comment]
Same for me too

**Comment by LeonNicholls** [comment]
You can file Cast SDK issues here: https://issuetracker.google.com/issues?q=componentid:190205%20status:open&s=modified_time:desc
