### ISSUE TITLE
Android CCL style library support?

### ISSUE THREAD

**Issue by olala7846** [googlecast/CastVideos-ios#24]
Hi @ianbarber, 
I'm not sure that if I should ask this here, so please let me know if I should ask it somewhere else :smile: 
Im an iOS googlecast developer, and I recently noticed that for Android developers, they can easily develop a cast enable mobile app with basic elements such as mini controller, action bar buttons, cling ...  since Android CCL already provides these elements for them to customize. 
And I also notice that in this ios sample project, those elements are already implemented. so my question is. "is Google planning to add those elements into the google-cast-sdk in the future?" If not, can you(Google) consider opening a project maybe a "google-cast-sdk wrapper library" for iOS developers to create library that provides the similar basic UI elements that conforms to the design guideline( similar functionalities as Android CCL library)? 

I think this will help lots of iOS developers to make their app cast-enble.
Thanks for your time.

**Comment by ianbarber** [comment]
Good idea! We're working to bring some of the fundamental elements down into the SDK to make life easier for developers, so watch out for SDK updates in the future that provide more components for you.
