### ISSUE TITLE
Cast icon / device list not appearing

### ISSUE THREAD

**Issue by hinesro** [googlecast/CastVideos-ios#25]
I'm seeing the same issue for for all the iOS sample apps--the cast icon does not appear on initial launch. Setting the app ID to use the default receiver app (app id = "kGCKMediaDefaultReceiverApplicationID") does not fix this. The app should prompt to view available devices and allow connecting to devices if found. The readme indicates updating the app ID field but this alone isn't enough to make the sample app functional.

**Comment by naddaf** [comment]
Are you using double-quotes when you set the app id? You shouldn't, if you are; it should read like:
[ChromecastDeviceController sharedInstance].applicationID = kGCKMediaDefaultReceiverApplicationID;

**Comment by hinesro** [comment]
No, but the original code in the sample app looks like: [ChromecastDeviceController sharedInstance].applicationID = @"4F8B3483";
Updating the app ID to kGCKMediaDefaultReceiverApplicationID results in failure to build: "Use of undeclared identifier 'kGCKMediaDefaultReceiverApplicationID' ".

**Comment by hinesro** [comment]
After resetting the Chromecast a few times and verifying that devices are communicating across the same network, it's seeing my Chromecast. The issue must have been somewhere in my hardware setup rather than the code.
