### ISSUE TITLE
No cast devices despite having one ? 

### ISSUE THREAD

**Issue by fadylateef** [googlecast/CastVideos-ios#25]
I've used the sample app several times and never found my cast device "LG Smart TV" which is connected to the same network and can be cast with other published apps from store.

Also the log gives : 
```
2017-11-16 11:09:47.490786+0300 CastVideos-ios[529:96185] Logging 15, currently detected {(
    7,
    3,
    5,
    1,
    15
)}
```

Have tried all samples on the internet , and none working.
the app starts but no cast button 
![simulator screen shot nov 16 2017 10 26 56 am](https://user-images.githubusercontent.com/17549441/32880629-0eadc086-cab7-11e7-9b89-6aa36a83beb3.png)

**Comment by LeonNicholls** [comment]
Please test this with a Cast-enabled device such as chromecast. Apps such as YouTube use other discovery protocols and work with various non-cast devices too.
