### ISSUE TITLE
GCKNetworkReachability ([GCKNetworkReachability updateStatusFromFlags:])

### ISSUE THREAD

**Issue by Chevit** [googlecast/CastVideos-ios#26]
Sometimes application are crashing with exception:
Fatal Exception: NSInternalInconsistencyException updateStatus called with NULL _reachabilityRef

<img width="944" alt="screen shot 2015-07-20 at 1 13 35 pm" src="https://cloud.githubusercontent.com/assets/750928/8773943/2b86e4a4-2ee1-11e5-8e38-175da342710a.png">

**Comment by ianbarber** [comment]
Do you still see this in 2.7.1? There were some reachability fixes around that.

**Comment by chrisrecher** [comment]
Are you still seeing this issue?

**Comment by Chevit** [comment]
Nope :)
With latest SDK there are no crashes for [GCKNetworkReachability updateStatusFromFlags:]. 
Thank you.
