### ISSUE TITLE
How to init GCKDiscoveryManager ?

### ISSUE THREAD

**Issue by bishalg** [googlecast/CastVideos-ios#27]
From `GCKDiscoveryManager.h` it is clear that default initializer is unavailable.
```
/**
 * Default initializer is not available.
 */
- (instancetype)init NS_UNAVAILABLE;
```

Documentation Link - [Discovery Manager](https://developers.google.com/cast/docs/reference/ios/interface_g_c_k_discovery_manager#aafe90df1ad363c928205f9c36d4ca68e)
 
How are we supposed to create the instance of GCKDiscoveryManager ?

Why isn't there any advanced level sample code which shows manual creation the Device Scanner and connect to the Cast device. There should have been an example code project where we use custom button and manual method of creating session for connection.

**Comment by LeonNicholls** [comment]
Device discovery is managed by the Cast SDK. Please use the GUI widgets provided by the SDK to allow the user to select a cast device.

**Comment by bishalg** [comment]
@entertailion : thks ! but this thing is not mentioned in documentation or code. It would be helpful if it was mentioned in the documentation that its mange only by SDK. 
So it means there is no way to manually scan and list the devices ?

**Comment by LeonNicholls** [comment]
Manual scans are not supported.
