### ISSUE TITLE
- (instancetype)initWithFilterCriteria:(GCKFilterCriteria *)filterCriteria;

### ISSUE THREAD

**Issue by yevheniyZaychenko** [googlecast/CastVideos-ios#27]
Initialising scanner wit this method causes the scanner will never find my Chromecast device.

GCKFilterCriteria * filterCriteria = [GCKFilterCriteria criteriaForAvailableApplicationWithID:@"MY-APP-ID-HERE"];
 _scanner = [[GCKDeviceScanner alloc] initWithFilterCriteria:filterCriteria];

**Comment by entertailion** [comment]
You need to replace "MY-APP-ID-HERE" with your own app ID from the Google Cast Developer Console: https://cast.google.com/publish

**Comment by yevheniyZaychenko** [comment]
entertailion, Of course I replaced =), My app ID is "7FFA8CAD" and the code looks like this:
GCKFilterCriteria * filterCriteria = [GCKFilterCriteria criteriaForAvailableApplicationWithID:@"7FFA8CAD"];

But The receiver with this Id is not searchable...

**Comment by entertailion** [comment]
Does the app work with the default app id "4F8B3483"?
Did you add your Chromecast device to the developer console and did you use the Cast extension to confirm that you got the serial number correct?
Did you reboot the Chromecast to make sure you got the latest configuration?

**Comment by yevheniyZaychenko** [comment]
Our cast device has been published and it's working good with Android SDK.

**Comment by ianbarber** [comment]
Yeah, init wont be filtering. Can you attach some output to GCKLogger and see what it is logging? Have you added details for your iOS to your Cast app in the publishers console?

**Comment by chrisrecher** [comment]
Are you still seeing this issue?

**Comment by chrisrecher** [comment]
Closing issue, apparently stale or resolved.
