### ISSUE TITLE
Issue with Cast [cast.receiver.MediaQueue] ItemID should not be defined element at index: 0

### ISSUE THREAD

**Issue by bishalg** [googlecast/CastVideos-ios#28]
I am having an issue with casting

1. The Cast button does show the list of cast devices.
2. The device will receive the media information properly ( as it display title )
3. As soon as the title is displayed the media player does not play but rather displays the app name.

Refer Issue posted on Google+ Channel for problem video
https://plus.google.com/+bishalghimire/posts/6qmR5cDQtkL

Chrome Debug 
<img width="913" alt="screen shot 2018-01-07 at 9 17 41 am" src="https://user-images.githubusercontent.com/805689/34658484-91967992-f457-11e7-8692-4421a8d527d8.png">

Code 
<img width="857" alt="screen shot 2018-01-07 at 9 25 52 am" src="https://user-images.githubusercontent.com/805689/34658499-a7010338-f457-11e7-950c-82e82ce4e0bb.png">

**Comment by LeonNicholls** [comment]
Please provide a sample stream and file a bug in the public tracker: https://issuetracker.google.com/issues?q=componentid:190205%20status:open&s=modified_time:desc

**Comment by bishalg** [comment]
As @entertailion have suggested it looks like the issue was due to CORS for the media. 
Thanks!
