### ISSUE TITLE
MediaController can lose asset background image

### ISSUE THREAD

**Issue by CapnSpellcheck** [googlecast/CastVideos-ios#3]
After opening the media controller, then tapping on the Cast icon to open the casting session view (not sure what this is called in the SDK), then hitting Cancel, the background asset is gone. Screenshots attached
![simulator screen shot jul 28 2016 6 57 39 pm](https://cloud.githubusercontent.com/assets/512016/17235352/4e4406c6-54f5-11e6-9f34-dc1dc01ffcb8.png)
![simulator screen shot jul 28 2016 6 57 42 pm](https://cloud.githubusercontent.com/assets/512016/17235353/4e48f2b2-54f5-11e6-8ec5-fa88d97bdc99.png)

Is this an SDK issue or app issue?

**Comment by LeonNicholls** [comment]
We have released the Cast SDK 3.1 and updated the sample app. Please try again and see if you still have the issue.
