### ISSUE TITLE
Does not compile

### ISSUE THREAD

**Issue by kenroyandfamily** [googlecast/CastVideos-ios#30]
After a 'pod install' GoogleCastSDK-2.6.0 installs but it does not have "GCKMediaQueueItem".  Version 2.6.0 seems to be missing certain header files.

If I manually download 2.10.0 these header files are there.  I tried specifying 2.10.0 in the podfile but pod is unable to find that version.

**Comment by chrisrecher** [comment]
Hmm... v2.10.0 is available on CocoaPods. Could you share the output of running "pod install" with the unmodified Podfile?

**Comment by kenroyandfamily** [comment]
In order to get it to compile I had to change the XCode project to compile for 7.0 or above then run pod install.  It is currently set for 6.0 and that causes cocoapods to install Google Chromecask SDK 2.6.0 rather than 2.10.0.

**Comment by chrisrecher** [comment]
I see - I'll change that if it's not set correctly in the past xcodeproj file. Thanks for bringing this to my attention!

**Comment by chrisrecher** [comment]
The deployment target defaults to 7.0 in my testing.
