### ISSUE TITLE
queueInsertItem not insert more then 3 media item

### ISSUE THREAD

**Issue by PraveenCodeSwift** [googlecast/CastVideos-ios#30]
-(void)loadSelectedItemByAppending:(BOOL)appending
 {

    GCKSession *session = [GCKCastContext sharedInstance].sessionManager.currentSession;
    if ([session isKindOfClass:[GCKCastSession class]]) {
        GCKCastSession *castSession = (GCKCastSession *)session;
        if (castSession.remoteMediaClient) {
            GCKMediaQueueItemBuilder *builder = [[GCKMediaQueueItemBuilder alloc] init];
            builder.mediaInformation = selectedItem.mediaInfo;
            builder.autoplay = NO;
            builder.preloadTime = [[NSUserDefaults standardUserDefaults] integerForKey:@"preload_time_sec"];
            GCKMediaQueueItem *item = [builder build];
            if (castSession.remoteMediaClient.mediaStatus && appending) {
                NSLog(@"Count: %lu",castSession.remoteMediaClient.mediaStatus.queueItemCount);
                GCKRequest *request = [castSession.remoteMediaClient queueInsertItem:item
                                                                    beforeItemWithID:kGCKMediaQueueInvalidItemID];
                request.delegate = self;
            } else {
                GCKMediaRepeatMode repeatMode =
                castSession.remoteMediaClient.mediaStatus ? castSession.remoteMediaClient.mediaStatus.queueRepeatMode : GCKMediaRepeatModeOff;
                GCKRequest *request = [castSession.remoteMediaClient queueLoadItems:@[ item ]
                                                                         startIndex:0
                                                                       playPosition:0
                                                                         repeatMode:repeatMode
                                                                         customData:nil];
                request.delegate = self;
            }
        }
    }
}

Log:
 Count: 0
 Count: 1
 Count: 3
 Count: 3
 Count: 3

Unable to add more than three media item in remoteMediaClient queueInsertItem

**Comment by LeonNicholls** [comment]
This looks like it might be a bug with the Cast SDK. You can file an issue: https://issuetracker.google.com/issues?q=componentid:190205%20status:open&s=modified_time:desc
