### ISSUE TITLE
Application crashes on start on iOS 9.1 device

### ISSUE THREAD

**Issue by jamfive** [googlecast/CastVideos-ios#31]
CastVideos[2396:1326240] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderArray initWithObjects:count:]: attempt to insert nil object from objects[0]'

**Comment by chrisrecher** [comment]
Found a workaround - Go into CastVideos > Images and select CastFrameworkAssets.xcassets. In the right sidebar, change the Location from .../GoogleCastSDK-2.7.1-Release/... to .../GoogleCastSDK-2.10.0-Release/...

I will investigate the underlying issue.

**Comment by jamfive** [comment]
Thanks. That worked immediately.

**Comment by chrisrecher** [comment]
Fixed in commit 5f166c4b. The app contains a (somewhat hacky) link to the xcassets file containing the Cast icons to get around CocoaPods not fully supporting it. I missed updating the link target when the SDK version number changed. Thanks for catching this!
