### ISSUE TITLE
Seek to 15 forward/backword sec not-working 

### ISSUE THREAD

**Issue by PraveenCodeSwift** [googlecast/CastVideos-ios#33]
- (IBAction)didTapOnSeekForward:(id)sender {
    GCKCastSession *castSession =[GCKCastContextsharedInstance].sessionManager.currentCastSession;

    if ([castSession isKindOfClass:[GCKCastSession class]]) {
        if (castSession.remoteMediaClient) {
            GCKMediaSeekOptions *seek = [[GCKMediaSeekOptions alloc] init];
            seek.relative = YES;
            seek.resumeState = GCKMediaResumeStatePlay;
            seek.interval = 15000; // milisecounds
            [castSession.remoteMediaClient seekWithOptions:seek];
        }
    }
}
I want to seek 15 sec back and forward but its start from starting i am not getting what is the issue
Please also help me play next and prev videos in Queue.

**Comment by fabiosoft** [comment]
news?

**Comment by LeonNicholls** [comment]
You can file a bug: https://issuetracker.google.com/issues?q=componentid:190205%20status:open&s=modified_time:desc
