### ISSUE TITLE
Android TV Not Detected

### ISSUE THREAD

**Issue by rangav** [googlecast/CastVideos-ios#34]
Hi

I am using Google cast sdk 3.3.0 and it is working fine with Chromecast device.

But its not detecting Sony Android TV with chromecast built in.

Do we need any extra setup to make it work?

Thanks

**Comment by LeonNicholls** [comment]
Is this just for development or is your app already public?

**Comment by rangav** [comment]
The app is already in public

**Comment by LeonNicholls** [comment]
Does any other Cast-enabled apps discover that device? (Don't use YouTube or Netflix for testing this)
Have you tried to reboot the TV?

**Comment by rangav** [comment]
Well actually i dont have android TV to test, one of the user complained about this, so just checking if will work automatically or we need any extra setup.

**Comment by LeonNicholls** [comment]
It should just work, but there could be local networking issues that might affect discovery. If you find a way to reproduce the issue then file an issue: https://issuetracker.google.com/issues?q=componentid:190205%20status:open&s=modified_time:desc
