### ISSUE TITLE
iPhone X

### ISSUE THREAD

**Issue by veroce** [googlecast/CastVideos-ios#35]
Hi!

I am using chrome cast in a project and it's amazing but I have a problem when I run it in iPhone X. The app doesn't show properly. I attach a screenshot.

<img width="457" alt="iphonex" src="https://user-images.githubusercontent.com/9121369/38508361-4c2aaa80-3c1f-11e8-8131-05ec4046fd06.png">

Thanks in advance.
Regards

**Comment by jtromo** [comment]
This has been addressed.

**Comment by stephenfung98** [comment]
This issue is occurring again on the iPhone X sized devices.
