### ISSUE TITLE
GCKUICastContainerViewController -  android / ios descrepancy

### ISSUE THREAD

**Issue by johndpope** [googlecast/CastVideos-ios#37]
<img width="453" alt="screen shot 2018-04-10 at 15 42 30" src="https://user-images.githubusercontent.com/289994/38579747-f00bc5a6-3cd5-11e8-9272-bfcb6ad75b45.png">

is it possible to programmatically make this consistent?

**Comment by LeonNicholls** [comment]
You might be using a queue in one and not the other.
