### ISSUE TITLE
[question] Appropriate approach to multi device casting

### ISSUE THREAD

**Issue by ninokierulf** [googlecast/CastVideos-ios#4]
Use Case:
Device A starts casting
Device B starts casting to same reciever
Device A should resume local playback (should Device A disconnect?)

What is the appropriate or elegant approach.
At the moment, I'm using customData with device identifier tied to the remote media item.
In the metaDataUpdated, I check the customData and if the device is not equal to the device doing the check, I invoke endSession

Is there a more correct solution that uses the provided APIs instead?

**Comment by LeonNicholls** [comment]
For any Cast Device, multiple senders can connect and control the media playback. You shouldn't have to do anything explicit to get this behavior.
