### ISSUE TITLE
GCKUICastButton doesn't display

### ISSUE THREAD

**Issue by PedanIhor** [googlecast/CastVideos-ios#40]
GCKUICastButton doesn't display

**Comment by LeonNicholls** [comment]
What have you done to debug this?

**Comment by PedanIhor** [comment]
Nothing. From box. I installed pods and run it. So the same thing if I install the last version of SDK to clean project and create a cast context with default receiver. I use Xcode 9.4 and Swift 4.1

**Comment by LeonNicholls** [comment]
Did you register your cast device in the Google Cast Developer Console? Did you add your app id to the source code?

**Comment by PedanIhor** [comment]
I don't have a device. I'm waiting for delivery. But I want to make a simple sender app, while I'm waiting. For example to test how works GCKDiscoveryManager. 
If I use kGCKDefaultMediaReceiverApplicationID, Do I need to register?

**Comment by LeonNicholls** [comment]
You don't need to register if you use the default media receiver.

**Comment by brenwell** [comment]
Hey guys. I am also creating a sender app, and hitting the button seems to have zero effect. Is there something obvious I may have missed

**Comment by wnstkdyu** [comment]
Hi. I have a same issue. I added UIButton in storyboard and assigned as a `GCKUICastButton`, but Xcode showed me this error. 'Failed to render and update auto layout status...' Also, when running an app, nothing appeared.
