### ISSUE TITLE
Can't cast .m3u8 videos

### ISSUE THREAD

**Issue by bjimenezned** [googlecast/CastVideos-ios#48]
In the demo I replaced the default .mp4 MediaInformations with a .m3u8 video, the local player works fine and the video plays as expected, but when I try to cast it, it fails (Shows a blackscreen with the "SAMPLE" words on it).

This is the MediaInformation I'm using

```
let mediaInfo = GCKMediaInformation(contentID: "https://bitdash-a.akamaihd.net/content/MI201109210084_1/m3u8s/f08e80da-bf1d-4e3d-8899-f0f6155f6efa.m3u8", streamType: .buffered,
                                            contentType: "application/x-mpegURL", metadata: metadata,
                                            streamDuration: kGCKInvalidTimeInterval,
                                            mediaTracks: nil,
                                            textTrackStyle: nil, customData: nil)
```

And this are some of the logs the app is showing.

```
MediaViewController: sessionManager didStartSession <0x106567460: GCKCastSession; state = 2>
switchToRemotePlayback; mediaInfo is Optional(<0x105bcd930: GCKMediaInformation; contentID = https://bitdash-a.akamaihd.net/content/MI201109210084_1/m3u8s/f08e80da-bf1d-4e3d-8899-f0f6155f6efa.m3u8>)
loading media: Optional(<0x105bcd930: GCKMediaInformation; contentID = https://bitdash-a.akamaihd.net/content/MI201109210084_1/m3u8s/f08e80da-bf1d-4e3d-8899-f0f6155f6efa.m3u8>)
removeMediaPlayerObservers
removeMediaPlayerObservers
setNavigationBarStyle: Default
SHOW NavBar.
configureControls stopped
didTouchControl stopped
hideNavigationBar: did touch control
SHOW NavBar.
MediaViewController: sessionManager didStartSession <0x106567460: GCKCastSession; state = 2>
fullscreen=false
setMediaInfo
setMediaInfo
hideToolBar stopped
setMediaInfo
```

the logs shows that the media is being loaded to Chromecast but for some reason it's not playing properly. Any help? am I missing something in my MediaInformation or should be m3u8 loaded differently?

**Comment by LeonNicholls** [comment]
The words "SAMPLE" is due to using the sample receiver; you can use your own receiver instead or use the default media receiver.
Does the stream have DRM?

**Comment by bjimenezned** [comment]
Yes, I'm aware. My idea was to show I was using the same receiver app in the demo, however the issue also happens with the default receiver.
The m3u8 does not have DRM, I got it from https://bitmovin.com/mpeg-dash-hls-examples-sample-streams/

**Comment by LeonNicholls** [comment]
The issue is likely with your stream and not this sample or the Cast SDK. You can file an issue with the support team to debug: https://issuetracker.google.com/issues?q=componentid:190205%20status:open&s=modified_time:desc

**Comment by bjimenezned** [comment]
Not sure if it's a stream problem since I've tried with several and different .m3u8 videos and none of them works, that's why I asked if my implementation (GCKMediaInformation) was a correct one.

Could you please add some working .m3u8 videos to the cast demo app? it only shows mp4 videos and those work for me, but any m3u8 I try does not work

**Comment by bjimenezned** [comment]
Also the same .m3u8 works when casting from the web or android device

**Comment by LeonNicholls** [comment]
Your GCKMediaInformation looks fine. Please file an issue so the support team can help you debug your stream.

**Comment by bhaskarraj** [comment]
I am also facing the same issue. @bjimenezned have you managed to fixed this?

**Comment by abhayJangde92** [comment]
I am also facing the same issue. I have read over internet about the issue some says the issue with CORS headers . Can anyone have idea what CORS headers are required.???

@bjimenezned did you get any fix for the issue?
