### ISSUE TITLE
How to set color of title and cancel button of device chooser view controller?

### ISSUE THREAD

**Issue by tomkowz** [googlecast/CastVideos-ios#49]
I am trying to set different color of title and cancel button in navigation bar of a device chooser class.

It is displayed in `UINavigationController` and I already have `UIAppearance` styling done for `UINavigationController` in my app (for global style) but it seems the values are overridden in private `GCKUIDeviceConnectionViewController` class. 

I want to make title white but it stays black. How can I achieve that? Also I would like to make the title uppercase.

Thanks in advance!

**Comment by LeonNicholls** [comment]
All the styling options are listed in our docs: https://developers.google.com/cast/docs/ios_sender_styles
If that doesn't work for you, then you can file a feature request: https://issuetracker.google.com/issues?q=componentid:190205%20status:open&s=modified_time:desc

**Comment by NSDavidObject** [comment]
@tomkowz did you have any luck with this?

**Comment by tomkowz** [comment]
> @tomkowz did you have any luck with this?

Sorry, I don't remember, that was a long time ago.
