### ISSUE TITLE
No visible presentDefaultExpandedMediaControls

### ISSUE THREAD

**Issue by xtreme8210** [googlecast/CastVideos-ios#5]
Hi
I got 4 errors, please help
![2016-08-09 2 51 47](https://cloud.githubusercontent.com/assets/2245528/17507186/dae02ac0-5e40-11e6-8c1c-ff20762435b4.png)

**Comment by LeonNicholls** [comment]
Make sure you have the 3.1.1 version of the iOS Cast SDK.
