### ISSUE TITLE
GCKUICastButton doesn't display with iOS 12 Beta

### ISSUE THREAD

**Issue by marcborn** [googlecast/CastVideos-ios#53]
Hello..

The app is working on all my test devices, except an iPhone 6s with latest iOS 12 Beta.
When i start the youtube app on the same phone, i have a cast button and it works fine.
Any ideas?

bye Marc

**Comment by LeonNicholls** [comment]
Please file any SDK bugs here: https://issuetracker.google.com/issues?q=componentid:190205%20status:open&s=modified_time:desc
