### ISSUE TITLE
Device discovery not working on iOS 12

### ISSUE THREAD

**Issue by smatte** [googlecast/CastVideos-ios#54]
After building *Cast Videos* app using *Xcode 10.0 Beta 6* on a device with **iOS 12 beta 12** the cast to device dialog only displays "Nearby Device" but none of my ChromeCast. It works fine if I build the exact same app on iOS 11.4.1. Both devices are on the same wifi.

Any idea?

**Comment by LeonNicholls** [comment]
Please file any SDK bugs here: https://issuetracker.google.com/issues?q=componentid:190205%20status:open&s=modified_time:desc

**Comment by smatte** [comment]
Issue created: https://issuetracker.google.com/u/1/issues/115478929
