### ISSUE TITLE
Not found receiver device for chrome cast (iOS)

### ISSUE THREAD

**Issue by x3T4R4T0RN** [googlecast/CastVideos-ios#55]
In Googlecast SDK version 4.3.2 Cannot found receiver device. But in v.3 with GCKDeviceScanner it work.

I already test with GoogleHome app , Youtube  and sample v.3 app , It's founded

**Comment by LeonNicholls** [comment]
You can file any Cast SDK issues here: https://issuetracker.google.com/issues?q=componentid:190205%20status:open&s=modified_time:desc
