### ISSUE TITLE
Discovery not working at all

### ISSUE THREAD

**Issue by elwell-teachco** [googlecast/CastVideos-ios#56]
Downloaded this app and installed 4.3.2 using CocoaPods.  Running on iPhoneX, the app does not discover any devices (discovery list only shows 'Nearby devices').    

Works fine on simulator.

Our app under development showed this when we upgraded from 3.5.0 to 4x.   We've now reverted back to 3.5, in which discovery works fine, but want to use latest so we can implement variable playback rate.

Steps to reproduce:
1. Download CastVideos-ios
2. pod install (installs 4.3.2)
3. Run on device (NOT simulator). 
4. Click on ChromeCast button on right nav bar.
5. Displays only 'Nearby devices'.

**Comment by LeonNicholls** [comment]
Please file an issue: https://issuetracker.google.com/issues?q=componentid:190205%20status:open&s=modified_time:desc

**Comment by jtromo** [comment]
This issue should now be fixed on device.
