### ISSUE TITLE
How to set ScaleType for Background Image Expanded Controller?

### ISSUE THREAD

**Issue by jml2014101** [googlecast/CastVideos-ios#57]
I'm working on a ChromeCast implementation in iOS.
The ExpandedController presents a background image. In my case, this image does not fit to the screen and winds up cropping the left and right sides of the image.
What I believe is happening is that the image is being rendered with a ScaleType of Center or CenterCrop.
What I want is for the image to be drawn using FitCenter so that there is no cropping of the edges.

I can not find any methods to set this scale type.
Please help me, thanks

**Comment by jml2014101** [comment]
This is original video thumbnail:
http://prntscr.com/l7sef5

This is Google Cast Expanded Controller:
http://prntscr.com/l7seqn

Background image is very bad. I need fitCenter mode.

**Comment by LeonNicholls** [comment]
You can file a feature request: https://issuetracker.google.com/issues?q=componentid:190205%20status:open&s=modified_time:desc

**Comment by jml2014101** [comment]
So There is no this feature in current google cast sdk for now. correct?
