### ISSUE TITLE
App in Background disconnect device by closing socket

### ISSUE THREAD

**Issue by iris112** [googlecast/CastVideos-ios#58]
Hello.
My name is Filip
Thanks for your helpful source.
I'm using this to integrate and expand our project for casting media.
But i'm getting trouble with some issues.

- First, When the app goes into background, the google cast sdk close the socket, so my iphone disconnected from cast device.

> I need to keep the session and not disconnect.

- Second, when i disconnected from device, i retry to connect manually, but i'm getting the following errors.

> [GCKDeviceAuthChannel timerDidFire:] authentication timed out
> [GCKCastDeviceConnector deviceAuthChannel:didFailToAuthenticateWithError:] Not an authentic device, disconnecting.
> Error Domain=com.google.GCKError Code=3 "Device authentication failure" UserInfo={NSLocalizedDescription=Device authentication failure}

I don't understand why is that. When i try to connect first, there is no authentication error, but i retry to connect secondly, i'm getting authentication error.

Please help me.
This is urgen issue for our project.

Thanks.
Regards.

**Comment by LeonNicholls** [comment]
The SDK should reconnect automatically when the app goes into the foreground. If you are seeing different, then you can file a bug: https://issuetracker.google.com/issues?q=componentid:190205%20status:open&s=modified_time:desc

**Comment by iris112** [comment]
Hello @entertailion 
Thanks for your quick response.

But what about the following problem?

> [GCKDeviceAuthChannel timerDidFire:] authentication timed out
> [GCKCastDeviceConnector deviceAuthChannel:didFailToAuthenticateWithError:] Not an authentic device, disconnecting.
> Error Domain=com.google.GCKError Code=3 "Device authentication failure" UserInfo={NSLocalizedDescription=Device authentication failure}

It happend when i try to reconnect device.

Thanks.
Regards.

**Comment by LeonNicholls** [comment]
Please file that as a bug.
