### ISSUE TITLE
The SDK is gigantic starting with 4.3.x

### ISSUE THREAD

**Issue by pepasflo** [googlecast/CastVideos-ios#63]
Something went off the rails between 4.2 and 4.3 of the SDK.

```
$ ls -sh */GoogleCast.framework/GoogleCast
 46M GoogleCastSDK-ios-4.2.0/GoogleCast.framework/GoogleCast
631M GoogleCastSDK-ios-4.3.1_static/GoogleCast.framework/GoogleCast
```

631MB?  Is this a joke?

**Comment by jtromo** [comment]
Starting with version 4.3.1, releases to cocoapods were changed from dynamic to static libraries, hence the size change. The app will build and exclude the object files that are not used so the final app size may even be smaller than before. If you wish to download the smaller dynamic library, it is available on the developer site: https://developers.google.com/cast/docs/developers#ios_sender_api_library

**Comment by pepasflo** [comment]
Who can I talk to about reversing this decision?  For teams who check their dependencies into revision control, this means checking a 600+MB file into github every time an update to the SDK comes out.  For teams who don't check dependencies into revision control, this still means a dependency fetch for new devs / build automation which is hundreds of megabytes larger.  I just don't see how this decision was justified -- this is a terrible developer experience, any way you slice it.

**Comment by jtromo** [comment]
Thank you for explaining your pain points and how this decision has impacted your team. We are raising your concerns with the product team and will get back to you. In the meantime, here is a link to the dynamic library which is less than 57MB and will hopefully unblock you for now: https://dl.google.com/dl/chromecast/sdk/ios/GoogleCastSDK-ios-4.3.4_dynamic.zip

**Comment by pepasflo** [comment]
Thanks!  Re-reading my comment, my tone was a bit more on the asshole side than it should have been.  Thank you for being tolerant.

I've tried to create a podspec for 4.3.x dynamic version, but building fails with `ld: framework not found GoogleCast`.

I then tried a sanity check of hosting an exact copy of the 4.2.0 podspec in a git repo, and it also fails with an `ld` error.  Very strange.

Just to document that sanity-check, here's what I did:
- Create a new github repo
- Download a copy of `https://raw.githubusercontent.com/CocoaPods/Specs/master/Specs/8/1/2/google-cast-sdk/4.2.0/google-cast-sdk.podspec.json` into the repo.
- Change your `Podfile` to use e.g. `pod 'google-cast-sdk', :git => 'https://github.com/YOUR_ACCOUNT_HERE/google-cast-sdk.git'`
- `pod install`
- Build in Xcode
- `ld: framework not found GoogleCast`

Because the podspec is literally unaltered from the working 4.2.0 podspec, I suspect this is a bug in Cocoapods.

Here was my attempt at the dynamic podspec:

```
{
  "name": "google-cast-sdk-dynamic",
  "dependencies": {
    "Protobuf": "~> 3.0"
  },
  "version": "4.3.4",
  "license": {
    "type": "Commercial",
    "text": "https://developers.google.com/terms/"
  },
  "summary": "Framework for casting content to Google Cast devices (dynamically-linked version)",
  "description": "Google Cast is a screen-sharing technology that lets a user send and\ncontrol content like video from a small computing device like a phone,\ntablet, or laptop to a large display device like a television.\n\nA sender application running on the sender device uses the Google Cast\nAPI appropriate to its operating system to discover and transmit to the\nreceiver application running on the receiver device. You can use the\nsender APIs to enable your iOS app to send content to a large display.\n Your use of Google Cast SDK is subject to, and by using or downloading any of\nthe related files you agree to comply with, the Google APIs Terms of Service (https://developers.google.com/terms/)\nand the Google Cast SDK Additional Developer Terms of Service (https://developers.google.com/cast/docs/terms/).",
  "homepage": "https://developers.google.com/cast/",
  "authors": "Google, Inc.",
  "preserve_paths": "GoogleCastSDK-ios-4.3.4_dynamic/GoogleCast.framework/Modules/module.modulemap",
  "module_map": "GoogleCastSDK-ios-4.3.4_dynamic/GoogleCast.framework/Modules/module.modulemap",
  "source": {
    "http": "https://developers.google.com/cast/downloads/GoogleCastSDK-ios-4.3.4_dynamic.zip"
  },
  "platforms": {
    "ios": "9.0"
  },
  "frameworks": [
    "Accelerate",
    "AudioToolbox",
    "AVFoundation",
    "CFNetwork",
    "CoreBluetooth",
    "CoreData",
    "CoreGraphics",
    "CoreMedia",
    "CoreText",
    "Foundation",
    "MediaAccessibility",
    "MediaPlayer",
    "QuartzCore",
    "Security",
    "SystemConfiguration",
    "UIKit"
  ],
  "xcconfig": {
  },
  "subspecs": [
    {
      "name": "Core",
      "source_files": "GoogleCastSDK-ios-4.3.4_dynamic/GoogleCast.framework/Headers/*.h",
      "preserve_paths": "GoogleCastSDK-ios-4.3.4_dynamic/GoogleCast.framework",
      "requires_arc": true,
      "vendored_frameworks": [
        "GoogleCastSDK-ios-4.3.4_dynamic/GoogleCast.framework"
      ],
      "libraries": [
        "c++"
      ],
      "resources": [
        "GoogleCastSDK-ios-4.3.4_dynamic/GoogleCast.framework/GoogleCastCoreResources.bundle",
        "GoogleCastSDK-ios-4.3.4_dynamic/GoogleCast.framework/GoogleCastUIResources.bundle"
      ]
    }
  ]
}
```

**Comment by jtromo** [comment]
My apologies for the long delay, we are actively looking for the best solution to your issue and will let you know as soon as we have a resolution.

**Comment by pepasflo** [comment]
thanks so much!

**Comment by jtromo** [comment]
I've met with the SDK team and discussed options for hosting the dynamic library including hosting another CocoaPods. At this time, the overhead of maintaining it isn't something the team is able to commit to, but if you would like to host it yourself like you started to do with your podspec that be perfectly fine. 

I believe the missing step in your process is to add the repo to CocoaPods itself so it is able to find it using the steps found on the CocoaPods guides: 
https://guides.cocoapods.org/making/making-a-cocoapod.html
Or a private cocoapod:
https://guides.cocoapods.org/making/private-cocoapods.html 

I've done a couple personal projects hosting a private repo with CocoaPods and it took a bit to get up but maintaining it was pretty straightforward. 

There is also a stackoverflow question that discusses this topic: https://stackoverflow.com/questions/22298850/creating-private-cocoapods-repo-outside-github

**Comment by pepasflo** [comment]
Thanks for the update!
