### ISSUE TITLE
Change color of miniController slider progress view and Volume slider in connection controller

### ISSUE THREAD

**Issue by bjimenezned** [googlecast/CastVideos-ios#75]
I would assume that 
`GCKUIStyle.sharedInstance().castViews.mediaControl.sliderProgressColor = .green` and `GCKUIStyle.sharedInstance().castViews.deviceControl.sliderProgressColor = .green`  would work but it doesn't It only changes the color of the slider in the ExpandedController. 
 I don't see another way to change this colors in the [docs](https://developers.google.com/cast/docs/ios_sender/customize_ui)

Am I doing something wrong or is it a bug in the stlyer?

**Comment by bjimenezned** [comment]
I found a workaround for this issue by setting the appearance of UISlider and UIProgressView
```
UIProgressView.appearance().tintColor = .green
UISlider.appearance().tintColor = .green
```

Be careful of not setting the thumb tintColor or it will replace the slider thumb image used by google cast in the volume slider and ExtendedController with the generic one and it kind of mess the layout of the elements

**Comment by anjaneesh** [comment]
That’s actually expected behavior because the progress view of minicontroller is not the same control of the slider of expanded controller...
@jtromo can you please confirm whether we support customizing the color of progressives in minicontroller.

**Comment by jtromo** [comment]
According to the [table](https://developers.google.com/cast/docs/ios_sender/customize_ui#table_of_views_and_styles), the correct command should be:

```
GCKUIStyle.sharedInstance().castViews.mediaControl.miniController.sliderProgressColor = .green
```

```
GCKUIStyle.sharedInstance().castViews.deviceControl.connectionController.sliderProgressColor = .green
```

You need to drill all the way down to the element you are trying to access. Please reopen if those don't work.

**Comment by bjimenezned** [comment]
I couldn't test before but now I did and is not working as it should, the default color is still showing

**Comment by tocute** [comment]
I still can not change the slider color of mini_controller

GCKUIStyle.sharedInstance().castViews.mediaControl.miniController.sliderProgressColor
