### ISSUE TITLE
No devices detected/device scannner not scanning when toggling airplane mode from within app

### ISSUE THREAD

**Issue by tomlindeman** [googlecast/CastVideos-ios#8]
We've implemented logic to reconnect to devices as they come online, but we're running into an issue where the user swipes up to reveal the control center and turns airplane mode on, then repeats the action to turn airplane mode back off. When this occurs, all the devices go offline as expected, but the deviceScanner will not start scanning (with a breakpoint I see the _scanning property's value as NO) even after I call startScan. No devices are ever detected, presumably because the scanner is not and will not scan until I background the app and then return to it. Once backgrounding/returning to the app occurs, the scanner starts scanning and devices are immediately detected and come online. Is there anything else I can do to force the deviceScanner to start scanning without having to background and return to the app?

**Comment by tomlindeman** [comment]
Also, this doesn't occur 100% of the time, but if you stay in the app and continue toggling airplane mode on and off from the control center, you'll wind up in this state - usually for me by the 3rd try.

**Comment by LeonNicholls** [comment]
Are you using the v3 version of the iOS SDK?

**Comment by tomlindeman** [comment]
Looks like Bundle version 3.1.1

**Comment by LeonNicholls** [comment]
If you have a way to reproduce this issue, then please file a bug against the iOS SDK: https://code.google.com/p/google-cast-sdk/issues/list
