### ISSUE TITLE
GCKUIStyle.sharedInstance() crashes app

### ISSUE THREAD

**Issue by sky-digital** [googlecast/CastVideos-ios#81]
When calling `GCKUIStyle.sharedInstance()` the app crashes with the following message:

`Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSDictionaryM setObject:forKey:]: object cannot be nil (key: playImage)'`

I'm using Xcode 11.3 and SDK version 4.4.4.

Does anyone know how to solve?

**Comment by jtromo** [comment]
Did you set the shared instance on the context first like this? https://github.com/googlecast/CastHelloVideo-ios/blob/b933167f2bd283458193e06a41a8d525271ea456/CastHelloVideo-swift/Classes/AppDelegate.swift#L32

**Comment by dogo** [comment]
Could be related to #72  ?

**Comment by majeedyaseen** [comment]
I am facing the same issue as my project is crashing on launch with the same exception on ios13. However if I run the same project on iOS 13 below versions it runs fine. Anybody got any solution for this. My current google-cast-sdk version is 4.3.3. 

@jtromo

**Comment by travisbader** [comment]
Any update on this issue?  I am facing the same issue and am on the latest version of the Cast SDK

**Comment by travisbader** [comment]
Sounds like maybe someone forgot to call self = [super init]

https://stackoverflow.com/questions/57949568/returned-nil-from-traitcollection-which-is-not-allowed-in-xcode-11-beta

**Comment by jtromo** [comment]
For any issues unrelated to the sample, please file an issue with the SDK so it can get the proper attention and include details to reproduce: https://developers.google.com/cast/support#report_issues

That said, I tried adding the following lines [here](https://github.com/googlecast/CastVideos-ios/blob/master/CastVideos-swift/Classes/AppDelegate.swift#L104) and did not experience a crash on iOS 13 with the latest SDK. 

```
// Get the shared instance of GCKUIStyle
let castStyle = GCKUIStyle.sharedInstance()
// Set the property of the desired cast widget.
castStyle.castViews.mediaControl.miniController.bodyTextColor = UIColor.red
// Refresh all currently visible views with the assigned styles.
castStyle.apply()
```

If you are able to include steps for how to reproduce on the ticket you file that will be extremely helpful.

**Comment by travisbader** [comment]
I do not see it in the sample however I can demonstrate it with this very simple app.  The exact same code in xamarin vs swift crashes in xamarin and succeeds in swift:

```
public override void FinishedLaunching(UIApplication application)
{
	var criteria = new DiscoveryCriteria(DiscoveryCriteria.DefaultMediaReceiverApplicationId);
	CastContext.SetSharedInstance(new CastOptions(criteria));

	var castContainerVC = CastContext.SharedInstance.CreateCastContainerController(new UINavigationController(new UIViewController()));

	Window = new UIWindow(UIScreen.MainScreen.Bounds);
	Window.RootViewController = castContainerVC;
	Window.MakeKeyAndVisible();
}
```

```
  func applicationDidFinishLaunching(_: UIApplication) {
    let criteria = GCKDiscoveryCriteria(applicationID: kGCKDefaultMediaReceiverApplicationID)
    GCKCastContext.setSharedInstanceWith(GCKCastOptions(discoveryCriteria: criteria))

    let castContainerVC = GCKCastContext.sharedInstance().createCastContainerController(for: UINavigationController(rootViewController: UIViewController()))

    window = UIWindow(frame: UIScreen.main.bounds)
    window?.rootViewController = castContainerVC
    window?.makeKeyAndVisible()
  }
```

**Comment by ashnfb** [comment]
I have been having this same issue with react-native-google-cast, which is using version 4.3.0 of the googlecast-sdk (hardcoded in the podspec).  When I use the non-bluetooth sdk, it uses 4.4.8, which doesn't produce the error.

```
'react-native-google-cast', :path => '../node_modules/react-native-google-cast/ios', :subspecs => [
    'NoBluetooth'
  ]
```

**Comment by jtromo** [comment]
Please file an issue with https://github.com/react-native-google-cast/react-native-google-cast as react-native-google-cast is not officially supported and 4.3.0 is very old.

If you find an SDK issue, please file an issue with the SDK so it can get the proper attention and include details to reproduce: https://developers.google.com/cast/support#report_issues
