### ISSUE TITLE
Introductory overlay starts way up in the view controller

### ISSUE THREAD

**Issue by dPackumar** [googlecast/CastVideos-ios#9]
The `GCKCastContext.sharedInstance().presentCastInstructionsViewControllerOnce()` shows the instructions but its not aligned properly and is way up, the OK button almost ends at navigation bar. The apps root view controller is a UITabBarController and has the Cast button on the navigation bar. Anyway that i can set the alignment ?

**Comment by LeonNicholls** [comment]
Have you looked at the latest release of the Cast iOS SDK which provides lots of ways to customize the SDK widgets: https://developers.google.com/cast/docs/ios_sender_styles

**Comment by dPackumar** [comment]
Yes i have and i am using 3.3 SDK, the link mentions about how i can customize the font and color and not the position of the screen itself.

**Comment by LeonNicholls** [comment]
Please file an issue on our tracker: https://code.google.com/p/google-cast-sdk/issues/list
